
tasks:
  - init: npm install && npm run build
    command: npm run start



vscode:
  extensions:
    - PKief.material-icon-theme
    - dbaeumer.vscode-eslint
    - christian-kohler.npm-intellisense
