
tasks:
  - init: npm install && npm run build && npm install -g @nestjs/cli
    command: npm run start



vscode:
  extensions:
    - PKief.material-icon-theme
    - dbaeumer.vscode-eslint
    - christian-kohler.npm-intellisense
